### ISSUE TITLE
Did you try appimaged?

### ISSUE THREAD

**Issue by probonopd** [joe733/appimage_file_associator#1]
Did you try the optional `appimaged` daemon? it does this kind of thing automagically.

**Comment by joe247** [comment]
Hi @probonopd, thanks for taking interest in this repository.

> Did you try the optional `appimaged` daemon? 

No I've not tried the daemon, but am I right in saying that it runs in the background all the time?

This python script simply runs once to associate file types to AppImages. There's a small issue, when the script is run multiple times it simply appends the mime files, even if the association intact. It's a redundancy, which I'll rectify it as soon as possible.

**Comment by probonopd** [comment]
Yes, the the optional `appimaged` daemon runs in be background so that it can create desktop files when AppImages come and go on the system.
